# Generated by Django 5.1.7 on 2025-04-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicbook',
            name='is_featured',
        ),
    ]
